// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct (non-pooled) connection to Postgres.
    // Runtime queries use the pooled DATABASE_URL via the pg adapter in src/lib/prisma.ts instead.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
